---
title: "Lb_2_Tsukaiev"
output: html_document
date: "2024-11-12"
---
# Зміст
- [Поділ значень полів](#поділ-значень-полів)
- [Середнє значення стовпців](#середнє-значення-стовпців)
- [Висновки](#висновки)

```{r}
# Завантаження бібліотеки
library(dplyr)

# Використовуємо вбудований набір даних iris
data(iris)
```

## Поділ значень полів

```{r}
# 1. Поділ значень полів, імена яких закінчуються на "Length", на середнє значення за цими стовпцями
iris_normalized <- iris %>%
  mutate(across(ends_with("Length"), ~ . / mean(., na.rm = TRUE)))

# Результат після виконання завдання 1
print("Ірис з нормалізованими стовпцями, що закінчуються на 'Length':")
print(head(iris_normalized))
```

## Середнє значення стовпців

```{r}
# 2. Середнє значення стовпців, що починаються на "Sepal", згруповане по стовпцю Species
iris_summary <- iris %>%
  group_by(Species) %>%
  summarise(across(starts_with("Sepal"), mean, na.rm = TRUE))

# Результат після виконання завдання 2
print("Середні значення стовпців, що починаються на 'Sepal', згруповані за 'Species':")
print(iris_summary)

```

## Висновки

У даній лабораторній роботі було проведено детальний аналіз даних з використанням пакету dplyr та бібліотеки vroom. 